// <auto-generated />
namespace Code_First_Tutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class shoppingdb1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shoppingdb1));
        
        string IMigrationMetadata.Id
        {
            get { return "202409120648348_shoppingdb1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
