using System;
using System.Linq;

namespace LINQTOSQL
{
    class _03_Get_Query_String
    {
        public static void GetSQLQuery()
        {
            // view the SQL Query generated by LINQ Query.

            // Three types to view the SQL Query
            DataClasses1DataContext dc = new DataClasses1DataContext();

            // write the linq query
            var query = from emp in dc.Employees
                        where emp.ID == 10 || emp.ID == 20
                        select emp;
            // view its equivalent sql query 

            // using log property of Datacontext
            dc.Log = Console.Out;

            // using to string method
            Console.WriteLine(query.ToString());

            // using GetCommand() method of Datacontext
            Console.WriteLine(dc.GetCommand(query).CommandText);


        }
    }
}
