//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial
{
    using System;
    
    public enum Roles : int
    {
        Software = 1,
        Hardware = 2,
        FullStack = 3
    }
}
