//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCheck
    {
        public string name { get; set; }
        public int rollno { get; set; }
        public string school { get; set; }
        public int id { get; set; }
        public byte[] rowversion { get; set; }
    }
}
